In [6]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array)
reShape = array.reshape(2,5)
print(reShape)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
import numpy as np
array1 = np.arange(1,21)
print(array1)
print(array1[5:15])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15]


In [17]:
import numpy as np
array2 = np.arange(1,21)
print(array2)
meanArr = np.mean(array2)
print(meanArr)
medianArr = np.median(array2)
print(medianArr)
standardDev = np.std(array2)
print(standardDev)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
10.5
10.5
5.766281297335398


In [32]:
import numpy as np
x = np.random.randint(5,30,(3,4))
print(x)
y = np.random.randint(50,60,(4))
print(y)

substract = y-x
print(substract)

[[21 29 24 26]
 [26 14 20  8]
 [ 6 14 15 19]]
[52 53 52 58]
[[31 24 28 32]
 [26 39 32 50]
 [46 39 37 39]]


In [2]:
import pandas as pd

dataFrame = {"Name":["Anu","Sinu","Manu","Linu","Sonu","Divya","Midhu","Vidhu","Binu","Dinu"],
             "Age":[20,21,30,22,31,22,26,19,27,32],
             "Gender":["Female","Female","Male","Female","Male","Female","Male","Male","Male","Female"]}
outPut = pd.DataFrame(dataFrame)
outPut


,Name,Age,Gender
0,Anu,20,Female
1,Sinu,21,Female
2,Manu,30,Male
3,Linu,22,Female
4,Sonu,31,Male
5,Divya,22,Female
6,Midhu,26,Male
7,Vidhu,19,Male
8,Binu,27,Male
9,Dinu,32,Female


In [45]:
outPut["Occupation"]=["Programmer","Manager","Analyst","Manager","Analyst","Programmer","Manager","Programmer","Analyst","Manager"]
outPut


,Name,Age,Gender,Occupation
0,Anu,20,Female,Programmer
1,Sinu,21,Female,Manager
2,Manu,30,Male,Analyst
3,Linu,22,Female,Manager
4,Sonu,31,Male,Analyst
5,Divya,22,Female,Programmer
6,Midhu,26,Male,Manager
7,Vidhu,19,Male,Programmer
8,Binu,27,Male,Analyst
9,Dinu,32,Female,Manager


In [60]:
print(outPut[outPut["Age"]>=30 ])


   Name  Age  Gender Occupation
2  Manu   30    Male    Analyst
4  Sonu   31    Male    Analyst
9  Dinu   32  Female    Manager


In [62]:
outPut.to_csv('Dataframe_data.csv', index=False)
newData =  pd.read_csv('Dataframe_data.csv')
newData

,Name,Age,Gender,Occupation
0,Anu,20,Female,Programmer
1,Sinu,21,Female,Manager
2,Manu,30,Male,Analyst
3,Linu,22,Female,Manager
4,Sonu,31,Male,Analyst
5,Divya,22,Female,Programmer
6,Midhu,26,Male,Manager
7,Vidhu,19,Male,Programmer
8,Binu,27,Male,Analyst
9,Dinu,32,Female,Manager
